# Generated by Django 2.1.7 on 2019-04-07 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('password', models.CharField(max_length=128, verbose_name='password')),
                # ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Pass', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=50)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Is_Staff', models.BooleanField(null=True)),
                ('Is_Active', models.BooleanField(null=True)),
                ('Acc_Type', models.CharField(choices=[('P', 'Provider'), ('S', 'Seeker')], max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
