# Generated by Django 2.1.7 on 2019-04-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190407_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
